name: Deploy Medusa

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: medusakey

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@52-91-163-227 << 'EOF'
          cd my-medusa-store || exit
          git pull origin main || exit
          docker-compose down || exit
          docker-compose up -d || exit
        EOF
